[package]
default-run = "actix-admin"
edition = "2021"
name = "actix-admin"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

app = {path = "../app"}
configs = {path = "../configs"}
db = {path = "../db"}
#
# poem = {version = "1.3", features = ["static-files", "rustls", "compression", "multipart", "tokio-metrics"]}
#poem = {version = "1.3", features = ["static-files", "rustls", "compression", "multipart"]}
#web server
actix-web = "4"
#actix-http = "3"
# 静态文件服务
actix-files = "0"
actix-identity = "0"
actix-multipart = "0"
actix-web-actors = "4"
actix-form-data = "0.6"

#
tracing = "0.1"
tracing-appender = "0.2"
# tracing-log = "0.1"
tokio = {version = "1.17.0", features = ["rt-multi-thread", "macros", "time"]}
tracing-subscriber = {version = "0.3", features = ["json", "env-filter", "local-time", "registry"]}
